### PR TITLE
Calculate reprojection error.

### PR DESCRIPTION
**Pull request by zbynekwinkler**
This is the "simplest thing that could possibly work" regarding reprojection error. Calculates gradient with respect to 3D points positions in preparation for bundle adjustment.

Open question is about the best representation of orientation in 3D wrt optimization by gradient descent. Quaternions seem somewhat straight forward. Euler angles could be also used but one is never quite sure about which rotation is which.

### CODE REVIEW

**Comment by m3d** [comment]
Could you please change README.md to direct links for installation? (I suppose that requirements.txt would not help in this case). Thanks

**Comment by m3d** [comment]
https://conda.io/docs/install/quick.html
```
d:\>conda install autograd
Fetching package metadata ...........

PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - autograd

You can search for packages on anaconda.org with

    anaconda search -t conda autograd

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

**Comment by zbynekwinkler** [comment]
Done. In the future I intend to add travis and appveyor unit tests, so that will always contain up-to-date install instructions.

What I am most interested in the review is the readability of the code. I'd like the code to be easy to understand with minimum comments.

**Comment by mdspk** [comment]
Thanks, now it works :). I would already split it into two files (bundle.py and test_bundle.py) and somehow I am used to 2 empty lines from PEP8 (sorry for stupid comments). Maybe test_project() and test_rotate() into unittest and test_reprojection_error() keep with prints in the bundle.py

**Review by m3d — APPROVED** [review]

**Comment by zbynekwinkler** [comment]
> Open question is about the best representation of orientation in 3D wrt optimization by gradient descent. Quaternions seem somewhat straight forward. Euler angles could be also used but one is never quite sure about which rotation is which.

Any opinions about this?

**Comment by m3d** [comment]
I would start with Quaternions

**Comment by m3d** [comment]
? delete branch?

**Pull request merged**
